config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  resources :line_items, :except=>[:destroy,:new,:show,:edit,:index] # removes unwanted routes by negating route access
  resources :carts
  resources :orders, :except=>[:show,:edit] # removes unwanted routes by negating route access
  root 'homepage#index', as: 'homepage_index'
  get 'contact', to: 'homepage#contact'
  get 'admin', to: 'homepage#admin'
  get 'collectables/index'
  get 'music/index'
  get 'movies/index'
  get 'carts/show'
  get 'movies' , to:  'movies#index'
  get 'collectables' , to:  'collectables#index'
  #get 'orders' , to:  'orders#index'
  get 'music' , to:  'music#index'
  post 'request_contact', to: 'homepage#request_contact'
  #resources :catagories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  include CurrentCart # INCLUDED CURRENTCART HELPER MODULE TO SET CURRENT CART TO CURRENT USER_CART
  before_action :set_cart #SETS CARTTS
  def index
    @products = Product.order(:category) # GETS PRODUCTS FILTERED BY THEIR category
    @orders = Order.order(:id) # GETS PRODUCTS FILTERED BY THEIR category
  end
  def contact # MADE FOR MAILER AND CONTACT PAGE

  end
  def request_contact #MADE FOR MAILER AND CONTACT PAGE
    name = params[:name] #NAME AND PRAMS
    email = params[:email] # EMAIL AND PARAMS
    telephone = params[:telephone] #TELEPHONE AND PARAMS
    message = params[:message] #MESSAGE AND PARAMS
    if email.blank? # IF EMAIL IS BLANK FLASH ALERT IS PRODUCED
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now # SEND EMAIL NOT CONNECTED TO STMP YET
      flash[:notice] = I18n.t('home.request_contact.email_sent') #NOTICE THAT MAILER HAS BEEN SENT
    end
    redirect_to homepage_index_url #AFTER MAIL HAS BEEN SENT REDIRECTS TO HOMEPAGE
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/contact.html.haml
%body
  %header.bg-dark.py-5
    .container.px-4.px-lg-5.my-5
      .text-center.text-white
        %h1.display-4.fw-bolder= t('.title')
        %p.lead.fw-normal.text-white-50.mb-0=t('.subtitle')

.container{:style => "border:0"}
  .row.gx-4.gx-lg-5.row-cols-2.row-cols-md-3
    .col.mb-5.text-center

    = form_tag request_contact_path, method: 'post' do
      %br
      .field
        = label_tag :name, t('.name')
        = text_field_tag :name, '', title: t('.enter_name'), size: 50 , class:"form-control"
      .field
        = label_tag :email, t('.email')
        = email_field_tag :email, '', title: t('.enter_email'), class:"form-control"
      .field
        = label_tag :telephone, t('.telephone')
        = telephone_field_tag :telephone, '', title: t('.enter_telephone'), class:"form-control"
      .field
      = label_tag :message, t('.message')
      = text_area_tag :message, '', title: t('.enter_message'), size: 100, class:"form-control"
      %br
      .actions
      %center
        = submit_tag t('.submit'), class:"btn btn-primary"
      

app/views/homepage/index.html.haml
%body
-if current_user && current_user.admin
  %header.bg-dark.py-5
    .container.px-4.px-lg-5.my-5
      .text-center.text-white
        %h1.display-4.fw-bolder=t('.titlea')
        %p.lead.fw-normal.text-white-50.mb-0=t('.subtitlea')

  %table.table.table-light.table-striped
    %thead
      %tr
        %th{:scope => "col"}=t('.col1')
        %th{:scope => "col"}=t('.col2')
    %tbody
      %tr
        %td
          = column_chart @products.group(:title).sum(:supply), width: "1000px", height: "500px", colors: ["#b00", "#666"],xtitle: "Products", ytitle: "Supply"
        %td
          %table.table.table-light.table-dark
            %thead
              %tr
                %th{:scope => "col"}=t('.col3')
                %th{:scope => "col"}=t('.col4')
                %th{:scope => "col"}=t('.col5')
            %tbody
              - @products.each do |product|
                -if product.supply <= 0
                  %tr
                    %td
                      = product.title
                    %td
                      = product.description
                    %td
                      =t('.col6')
  %table.table.table-light.table-striped
    %thead
      %tr
        %th{:scope => "col"}=t('.col7')
        %th{:scope => "col"}=t('.col8')
    %tbody
      %tr
        %td
          = line_chart @orders.group(:created_at).sum(:id), width: "1000px", height: "500px", colors: ["#b00", "#666"],xtitle: "Date Order Placed", ytitle: "Order ID"
        %td
          %table.table.table-light.table-dark
            %thead
              %tr
                %th{:scope => "col"}=t('.col9')
                %th{:scope => "col"}=t('.col10')
                %th{:scope => "col"}=t('.col11')
            %tbody
              - @orders.each do |order|
                %tr
                  %td
                    = order.id
                  %td
                    = order.email
                  %td
                    =t('.col12')

-else
  %header.bg-dark.py-5
    .container.px-4.px-lg-5.my-5
      .text-center.text-white
        %h1.display-4.fw-bolder=t('.title')
        %p.lead.fw-normal.text-white-50.mb-0=t('.subtitle')

  #myCarousel.carousel.slide{"data-ride" => "carousel"}
    / Indicators
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
      %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
      %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
    / Wrapper for slides
    .carousel-inner
      .item.active
        %img{:alt => "collectables", :src => "assets/collectables.jpg", :style => "width:100%;"}/
      .item
        %img{:alt => "movies", :src => "assets/movies.jpg", :style => "width:100%;"}/
      .item
        %img{:alt => "music", :src => "assets/music.jpg", :style => "width:100%;"}/
    / Left and right controls
    %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
      %span.glyphicon.glyphicon-chevron-left
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
      %span.glyphicon.glyphicon-chevron-right
      %span.sr-only Next


  / Section
  %section.py-5
    .container.px-4.px-lg-5.mt-5
      .row.gx-4.gx-lg-5.row-cols-2.row-cols-md-3.row-cols-xl-4.justify-content-center
        - @products.each do |product|
          .col.mb-5
            .card.h-100
              / Product image
              = image_tag(product.image_url,height:325 )
              / Product details
              .card-body.p-4
                .text-center
                  / Product name
                  %h4.fw-bolder= product.title
                  / Product price
                  %span.price= number_to_currency(product.price)
                %br
                  %p.fw-bolder= product.description
              -if(product.supply <= 0)
                %h4.fw-bolder{:style => "color:#fb5195"}
                  %center=t('.Outstock')
              -else
                / Product actions
                .card-footer.p-4.pt-0.border-top-0.bg-transparent
                  .text-center
                    = button_to(t('.carttext'), line_items_path(product_id: product) , class: "btn btn-outline-dark mt-auto")