config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  resources :line_items, :except=>[:destroy,:new,:show,:edit,:index] # removes unwanted routes by negating route access
  resources :carts
  resources :orders, :except=>[:show,:edit] # removes unwanted routes by negating route access
  root 'homepage#index', as: 'homepage_index'
  get 'contact', to: 'homepage#contact'
  get 'admin', to: 'homepage#admin'
  get 'collectables/index'
  get 'music/index'
  get 'movies/index'
  get 'carts/show'
  get 'movies' , to:  'movies#index'
  get 'collectables' , to:  'collectables#index'
  #get 'orders' , to:  'orders#index'
  get 'music' , to:  'music#index'
  post 'request_contact', to: 'homepage#request_contact'
  #resources :catagories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user, :optional => true
  def add_product(product) # method added to add products in lineitems linked to current cart
    current_item = line_items.find_by(product_id: product.id) # current line item set by fineding lineitem from product id
    if current_item
      current_item.quantity += 1 # incement line item quanity if current item exists
      #so in cart if you add 2 of the same product types it says 2 harry potter book hence harry potter book is a product you create a line item of this product by linking product id if the line item exists it justs adds to the item quanity.
    else
      current_item = line_items.build(product_id: product.id) # if current item doesnot exsist make new current item and build it using product id. then next time this product will be added to cart no new line item will be created old line item will be added by quanity + 1
    end
    current_item
  end
  def total_price # caluclates totale price of all items in cart by adding them.
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user! # authenticates user before making cart
  before_action :set_cart, only: %i[ show edit update destroy ]
  # redurects user to homepage if they try to acess anyone elses cart
  before_action do
    redirect_to homepage_index_url unless @cart && current_user && current_user.cart.id == @cart.id # checls for current_user.cart.id with the cart.id entered and if false then redirects to homepage
  end
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart # rescues form active record not found by invoking invalid cart method described in the bottom of the file
  # GET /carts or /carts.json
  def index # idexes all carts to @cart
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show

  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    # this lines are added to find the products before the cart is emptied and restore the supply that was taken form products to the cart.
    # so if in products table product a has a supply of 10 and user puts 3 of this product in his cart the supply in product table will change form 10 to 7 and this action returns the 3 items in cart when cart is emptied
    @cart.line_items.each do |item|
      product = Product.find(item['product_id'])
      product.update_columns(supply: product.supply + item.quantity) # updates the product supply by returning products to table
    end
    if current_user.present? # if current user is present then cart is initalized to be current_user cart and then through current_user.current_cart is detroyed.
      @cart = current_user.current_cart
      current_user.current_cart.destroy
    end
    @cart.destroy if @cart.id == session[:cart_id] # cart is destroyed if session cart id is equal to current cart id
    current_user.current_cart.destroy
    session[:cart_id] = nil # session id is made to be nil to remove the cart session
    respond_to do |format|
      format.html { redirect_to homepage_index_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart # if attept to acess invalid cart it will give error and send the user back to homepage
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to homepage_index_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
%link{href: "Homepage-MCM-webstore/css/styles.css", rel: "stylesheet"}/

%body
  %header.bg-dark.py-5
    .container.px-4.px-lg-5.my-5
      .text-center.text-white
        %h1.display-4.fw-bolder Your Cart
        %p.lead.fw-normal.text-white-50.mb-0 Happy Shopping !!!
  / Section
  %section.py-5
    .container.px-4.px-lg-5.mt-5
    %table.table.table-light.table-striped
      %thead
        %tr
          %th{:scope => "col"} Items
          %th{:scope => "col"}
          %th{:scope => "col"} Title
          %th{:scope => "col"} Price

      %tbody
        - @cart.line_items.each do |item|
          %tr
            %td
              = item.quantity
            %td
              = image_tag(item.product.image_url, class: 'icon_image', width: 100, height:100)
            %td
              = item.product.title
            %td
              = item.product.price
        %tr.total_line
          %td{:colspan => "2"} Total
          %td.total_cell= number_to_currency(@cart.total_price)
    %br
    = button_to 'Empty cart', @cart, method: :delete, |
      data: { confirm: 'Are you sure?' }              |
    %br

    = link_to 'Edit', edit_cart_path(@cart)
    \|
    = link_to 'Back', carts_path

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts
%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
%body
  / Section
  - if @cart.line_items.length() == 0
    %header.bg-dark.py-4
      .container.px-4.px-lg-5.my-5
        %h2.display-4.fw-bolder{:style => "color:#fb5195"}
          %center=t('.etitle')
    %section.py-5
      .container.px-4.px-lg-5.mt-5
        %center
          %img{:alt => "Italian Trulli", :src => "https://c.tenor.com/An_jX6JYJ-AAAAAC/oh-no.gif"}/
  - else
    %header.bg-dark.py-5
      .container.px-4.px-lg-5.my-5
        .text-center.text-white
          %h2.display-4.fw-bolder=t('.title')
          %p.lead.fw-normal.text-white-50.mb-0=t('.subtitle')
    %section.py-5
      .container.px-4.px-lg-5.mt-5
      %table.table.table-active.table-striped
        %thead
          %tr
            %th{:scope => "col"}=t('.column1')
            %th{:scope => "col"}
            %th{:scope => "col"}=t('.column2')
            %th{:scope => "col"}=t('.column3')

        %tbody
          - @cart.line_items.each do |item|
            %tr
              %td
                = item.quantity
              %td
                = image_tag(item.product.image_url, class: 'icon_image', width: 100, height:100)
              %td
                = item.product.title
              %td
                = number_to_currency(item.product.price)
          %tr.total_line
            %td{:colspan => "2"}=t('.totalrow')
            %td{:colspan => "1"}
            %td.total_cell= number_to_currency(@cart.total_price)
    %center
      = link_to(t('.ecarttext'), @cart, method: :delete, data: { confirm:t('.ecartmsg') } , class: "btn btn-outline-dark mt-auto")
      \|
      = link_to(t('.checkout'), new_order_path, method: :get, class: "btn btn-outline-dark mt-auto")

app/views/carts/show2.html.haml
%link{href: "Homepage-MCM-webstore/css/styles.css", rel: "stylesheet"}/
%body
  %header.bg-dark.py-5
    .container.px-4.px-lg-5.my-5
      .text-center.text-white
        %h1.display-4.fw-bolder Your Cart
        %p.lead.fw-normal.text-white-50.mb-0 Happy Shopping !!!
  / Section
  %section.py-5
    .container.px-4.px-lg-5.mt-5
    %table.table.table-light.table-striped
      %thead
        %tr
          %th{:scope => "col"} Items
          %th{:scope => "col"}
          %th{:scope => "col"} Title
          %th{:scope => "col"} Price

      %tbody
        - @cart.line_items.each do |item|
          %tr
            %td
              = item.quantity x
            %td
              = image_tag(item.product.image_url, class: 'icon_image', width: 100, height:100)
            %td
              = item.product.title
            %td
              = item.product.price
        %tr.total_line
          %td{:colspan => "2"} Total
          %td.total_cell= number_to_currency(@cart.total_price)
    %br
    = button_to 'Empty cart', @cart, method: :delete, |
      data: { confirm: 'Are you sure?' }              |
    %br

    = link_to 'Edit', edit_cart_path(@cart)
    \|
    = link_to 'Back', carts_path

app/views/carts/showorg.html.haml
%p#notice= notice
%br
%br
%h2 Your Cart
%table
  - @cart.line_items.each do |item|
    %tr
      %td
        = item.quantity
        \×
      %td= item.product.title
      %td.item_price= number_to_currency(item.total_price)
  %tr.total_line
    %td{:colspan => "2"} Total
    %td.total_cell= number_to_currency(@cart.total_price)
= button_to 'Empty cart', @cart, method: :delete, |
  data: { confirm: 'Are you sure?' }              |
= link_to 'Edit', edit_cart_path(@cart)
\|
= link_to 'Back', carts_path
= link_to 'Cart Record', carts_path(@cart)