config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  resources :line_items, :except=>[:destroy,:new,:show,:edit,:index] # removes unwanted routes by negating route access
  resources :carts
  resources :orders, :except=>[:show,:edit] # removes unwanted routes by negating route access
  root 'homepage#index', as: 'homepage_index'
  get 'contact', to: 'homepage#contact'
  get 'admin', to: 'homepage#admin'
  get 'collectables/index'
  get 'music/index'
  get 'movies/index'
  get 'carts/show'
  get 'movies' , to:  'movies#index'
  get 'collectables' , to:  'collectables#index'
  #get 'orders' , to:  'orders#index'
  get 'music' , to:  'music#index'
  post 'request_contact', to: 'homepage#request_contact'
  #resources :catagories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true # belongs to order
  belongs_to :product, optional: true # belongs to product
  belongs_to :cart # belongs to cart

  def total_price # total price of line items so if we have 2 harry potter books total price would be quantity of line item * single line item price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart # INCLUDED CURRENTCART HELPER MODULE TO SET CURRENT CART TO CURRENT USER_CART
  before_action :authenticate_user! # authenticates user before making LINEITEMS AND LIMITS access
  before_action :set_cart, only: [:create] #SETS CART
  before_action :set_line_item, only: [:show, :edit, :update, :destroy] #sets line items beforeactiosn
  before_action :set_line_item, only: %i[ show edit update destroy ]


  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    # if current product in question has supply more then or equal to 1
    #then in update product table and decrement product supply in table by 1 as it has been added to lineitems
    product = Product.find(params[:product_id])
    if product.supply >= 1
      x = product.supply-1
      Product.update(params[:product_id],supply: x) # updates product supply by decremting 1
      @line_item = @cart.add_product(product)
      respond_to do |format|
        if @line_item.save
          format.html {} #redirect makes page repload hence we leave it e
          format.json { render :show, status: :created, location: @line_item }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @line_item.errors, status: :unprocessable_entity }
        end
      end
    else # if product supply is less then 1 then redirect to hompage as item is out of stock
      redirect_to homepage_index_url
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :product
    = f.text_field :product
  .field
    = f.label :cart
    = f.text_field :cart
  .actions
    = f.submit t('.submit')

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1=t('.title')

%table
  %thead
    %tr
      %th=t('.col1')
      %th=t('.col2')
      %th
      %th
      %th

  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product
        %td= line_item.cart
        %td= link_to t('.link1'), line_item
        %td= link_to t('.link2'), edit_line_item_path(line_item)
        %td= link_to t('.link3'), line_item, method: :delete, data: { confirm: t('.link3m') }

%br

= link_to t('.link4'), new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to t('.link1'), line_items_path

app/views/line_items/show.html.haml
%p
  %b Product:
  = @line_item.product
%p
  %b Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path